steps:
- name: 'docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/vincent-sandbox-prj/python-apps/bank-campaign-model', '.' ]

- name: 'docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/vincent-sandbox-prj/python-apps/bank-campaign-model' ]

- name: 'us-central1-docker.pkg.dev/vincent-sandbox-prj/python-apps/bank-campaign-model'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    python -m pytest

- name: 'gcr.io/cloud-builders/git'
  args: [ 'clone', 'https://github.com/qingvincentyin/model-training-repo.git' ]

- name: 'gcr.io/cloud-builders/gsutil'
  args: [ 'cp', 'model-training-repo/bank_campaign_model_training.py', 'gs://us-central1-mlops-airflow-e68760e9-bucket/dags' ]

images:
- 'us-central1-docker.pkg.dev/vincent-sandbox-prj/python-apps/bank-campaign-model'

options:
  logging: CLOUD_LOGGING_ONLY
